.steps:
# Install Go
- name: 'gcr.io/cloud-builders/curl'
  args: ['-O', 'https://dl.google.com/go/go1.21.3.linux-amd64.tar.gz']
- name: 'gcr.io/cloud-builders/tar'
  args: ['-xzf', 'go1.21.3.linux-amd64.tar.gz']
- name: 'gcr.io/cloud-builders/mv'
  args: ['go', '/workspace/go']

# Set up Go environment
- name: 'gcr.io/cloud-builders/bash'
  env:
    - 'GOROOT=/workspace/go'
    - 'GOPATH=/workspace/gopath'
    - 'PATH=/workspace/go/bin:$PATH'
  args:
    - '-c'
    - |
      echo "export GOROOT=/workspace/go" >> /root/.bashrc
      echo "export GOPATH=/workspace/gopath" >> /root/.bashrc
      echo "export PATH=/workspace/go/bin:$$PATH" >> /root/.bashrc
      source /root/.bashrc
      cd infrastructure
      go mod download
      go mod tidy
      go build
      go version

# Install Pulumi
- name: 'gcr.io/cloud-builders/curl'
  args: ['-fsSL', 'https://get.pulumi.com', '-o', 'get-pulumi.sh']
- name: 'gcr.io/cloud-builders/bash'
  args: ['bash', 'get-pulumi.sh']
  env:
    - 'PATH=/root/.pulumi/bin:$PATH'

# Navigate to the infrastructure directory and download Go dependencies
- name: 'gcr.io/cloud-builders/bash'
  env:
    - 'GOROOT=/workspace/go'
    - 'GOPATH=/workspace/gopath'
    - 'PATH=/workspace/go/bin:/root/.pulumi/bin:$PATH'
  args:
    - '-c'
    - |
      cd infrastructure
      go mod download
      go build

# Run Pulumi
- name: 'gcr.io/cloud-builders/bash'
  env:
    - 'GOROOT=/workspace/go'
    - 'GOPATH=/workspace/gopath'
    - 'PATH=/workspace/go/bin:/root/.pulumi/bin:$PATH'
    - 'PULUMI_ACCESS_TOKEN=${_PULUMI_ACCESS_TOKEN}'
  args:
    - '-c'
    - |
      cd infrastructure
      pulumi login
      pulumi stack select dev
      pulumi config set gcp:project ${PROJECT_ID}
      pulumi up --yes

# Build and push Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/gold-price-producer:${_VERSION}', '-f', 'Dockerfile-producer', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/gold-price-producer:${_VERSION}']

# Deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'gold-price-ingestion'
  - '--image'
  - 'gcr.io/${PROJECT_ID}/gold-price-producer:${_VERSION}'
  - '--region'
  - '${_REGION}'
  - '--set-env-vars'
  - 'GCS_BUCKET=gold-price-raw-data,GOLD_API_KEY=${_GOLD_API_KEY},GOLD_API_BASE_URL=https://www.goldapi.io/api,GOOGLE_CLOUD_PROJECT=${PROJECT_ID},PUBSUB_TOPIC=gold-price'
  - '--service-account'
  - 'goldprice-service-account@${PROJECT_ID}.iam.gserviceaccount.com'

substitutions:
  _VERSION: 'v1.0.0'
  _REGION: 'us-west1'
  _PULUMI_ACCESS_TOKEN: 'your-pulumi-access-token'
  _GOLD_API_KEY: 'your-gold-api-key'

options:
  logging: CLOUD_LOGGING_ONLY