name: Process Gold Price Data

on:
  schedule:
    - cron: '0 */1 * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual triggering

jobs:
  process-data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-cloud-pubsub google-cloud-bigquery google-cloud-storage
    
    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
    
    - name: Process Gold Price Data
      run: python cloud_functions.py
      env:
        PROJECT_ID: de-goldprice
        PUBSUB_TOPIC: gold-price
        BIGQUERY_DATASET: gold_price_dataset
        BIGQUERY_TABLE: gold_prices
        GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}